---
title: "Lab 00 - Hello IDS!"
author: "Lucio Di Meo"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Alfie", "Ismayil", 
           "Max", "Jonah", "Kate"),
  github_username = c("ACTC1512", "Ismayil_2007", 
                      "username 3", "username 4", "Kate_M_I"), 
  colour = c("Orange", "Blue", 
             "Light Blue", "Green","Black"),
  hobby = c("Poker", "Chess", 
            "Mountain Biking", "Cycling", ""),
  favourite_number = c(9, 27, 6, 1, 9.7)
  )

team_data
```

### Exercise 18

We now work on visualising our data.

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

It shows a barchart where the hieght corresponds to favourite number and
bar colour corresponds to their favourite colour for each person

